import { 
  FileText, FileImage, Layers, SplitSquareHorizontal, 
  Image as ImageIcon, ScanText, QrCode, FileArchive, 
  Briefcase, Eraser, FileDown, RotateCw, Unlock, Shield,
  ImagePlay, Sparkles, Bot, FileSignature, BrainCircuit
} from "lucide-react";
import { ReactNode } from "react";

export type ToolConfig = {
  id: string;
  slug: string;
  title: string;
  description: string;
  icon: any; // Using any for Lucide icon component type simplicity
  color: string;
  category: "PDF" | "Image" | "Utility" | "AI";
  isAi?: boolean;
};

export const toolsConfig: ToolConfig[] = [
  {
    id: "word-to-pdf",
    slug: "word-to-pdf",
    title: "Word to PDF",
    description: "Make DOC and DOCX files easy to read by converting them to PDF.",
    icon: FileText,
    color: "bg-blue-100 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400",
    category: "PDF",
  },
  {
    id: "pdf-to-word",
    slug: "pdf-to-word",
    title: "PDF to Word",
    description: "Easily convert your PDF files into easy to edit DOC and DOCX documents.",
    icon: FileImage,
    color: "bg-violet-100 text-violet-600 dark:bg-violet-900/30 dark:text-violet-400",
    category: "PDF",
  },
  {
    id: "merge-pdf",
    slug: "merge-pdf",
    title: "Merge PDF",
    description: "Combine PDFs in the order you want with the easiest PDF merger available.",
    icon: Layers,
    color: "bg-purple-100 text-purple-600 dark:bg-purple-900/30 dark:text-purple-400",
    category: "PDF",
  },
  {
    id: "split-pdf",
    slug: "split-pdf",
    title: "Split PDF",
    description: "Separate one page or a whole set for easy conversion into independent PDF files.",
    icon: SplitSquareHorizontal,
    color: "bg-fuchsia-100 text-fuchsia-600 dark:bg-fuchsia-900/30 dark:text-fuchsia-400",
    category: "PDF",
  },
  {
    id: "watermark-pdf",
    slug: "watermark-pdf",
    title: "Watermark PDF",
    description: "Stamp an image or text over your PDF in seconds. Choose the typography, transparency and position.",
    icon: ImageIcon,
    color: "bg-cyan-100 text-cyan-600 dark:bg-cyan-900/30 dark:text-cyan-400",
    category: "PDF",
  },
  {
    id: "compress-pdf",
    slug: "compress-pdf",
    title: "PDF Compress",
    description: "Reduce PDF file size without compromising on quality.",
    icon: FileDown,
    color: "bg-teal-100 text-teal-600 dark:bg-teal-900/30 dark:text-teal-400",
    category: "PDF",
  },
  {
    id: "rotate-pdf",
    slug: "rotate-pdf",
    title: "PDF Rotate",
    description: "Rotate your PDFs the way you need them. You can even rotate multiple PDFs at once!",
    icon: RotateCw,
    color: "bg-lime-100 text-lime-600 dark:bg-lime-900/30 dark:text-lime-400",
    category: "PDF",
  },
  {
    id: "unlock-pdf",
    slug: "unlock-pdf",
    title: "PDF Unlock",
    description: "Remove PDF password security, giving you the freedom to use your PDFs as you want.",
    icon: Unlock,
    color: "bg-red-100 text-red-600 dark:bg-red-900/30 dark:text-red-400",
    category: "PDF",
  },
  {
    id: "protect-pdf",
    slug: "protect-pdf",
    title: "PDF Protect",
    description: "Protect PDF files with a password. Encrypt PDF documents to prevent unauthorized access.",
    icon: Shield,
    color: "bg-green-100 text-green-600 dark:bg-green-900/30 dark:text-green-400",
    category: "PDF",
  },
  {
    id: "jpg-to-png",
    slug: "jpg-to-png",
    title: "JPG to PNG",
    description: "Convert JPG images to PNG with transparent backgrounds.",
    icon: ImageIcon,
    color: "bg-amber-100 text-amber-600 dark:bg-amber-900/30 dark:text-amber-400",
    category: "Image",
  },
  {
    id: "png-to-jpg",
    slug: "png-to-jpg",
    title: "PNG to JPG",
    description: "Convert PNG images to JPG format for smaller file sizes.",
    icon: ImageIcon,
    color: "bg-rose-100 text-rose-600 dark:bg-rose-900/30 dark:text-rose-400",
    category: "Image",
  },
  {
    id: "webp-converter",
    slug: "webp-converter",
    title: "WEBP Converter",
    description: "Convert images to and from the highly optimized WebP format.",
    icon: ImagePlay,
    color: "bg-sky-100 text-sky-600 dark:bg-sky-900/30 dark:text-sky-400",
    category: "Image",
  },
  {
    id: "ocr",
    slug: "ocr",
    title: "OCR Scanner",
    description: "Turn your scanned PDFs into searchable and selectable text documents.",
    icon: ScanText,
    color: "bg-orange-100 text-orange-600 dark:bg-orange-900/30 dark:text-orange-400",
    category: "PDF",
  },
  {
    id: "compress-image",
    slug: "compress-image",
    title: "Compress Image",
    description: "Compress JPG, PNG, and WEBP images while maintaining quality.",
    icon: ImageIcon,
    color: "bg-emerald-100 text-emerald-600 dark:bg-emerald-900/30 dark:text-emerald-400",
    category: "Image",
  },
  {
    id: "resize-image",
    slug: "resize-image",
    title: "Resize Image",
    description: "Resize images by defining new height and width pixels or by percentage.",
    icon: ImageIcon,
    color: "bg-indigo-100 text-indigo-600 dark:bg-indigo-900/30 dark:text-indigo-400",
    category: "Image",
  },
  {
    id: "crop-image",
    slug: "crop-image",
    title: "Crop Image",
    description: "Crop your image to the perfect size and ratio for social media or print.",
    icon: ImageIcon,
    color: "bg-yellow-100 text-yellow-600 dark:bg-yellow-900/30 dark:text-yellow-400",
    category: "Image",
  },
  {
    id: "heic-converter",
    slug: "heic-converter",
    title: "HEIC to JPG",
    description: "Convert Apple HEIC image format to standard JPG for maximum compatibility.",
    icon: ImageIcon,
    color: "bg-purple-100 text-purple-600 dark:bg-purple-900/30 dark:text-purple-400",
    category: "Image",
  },
  {
    id: "image-to-pdf",
    slug: "image-to-pdf",
    title: "Image to PDF",
    description: "Convert JPG, PNG, or WEBP images into a single PDF document.",
    icon: FileText,
    color: "bg-blue-100 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400",
    category: "PDF",
  },
  {
    id: "resume-builder",
    slug: "resume-builder",
    title: "Resume Builder",
    description: "Create professional resumes in minutes with our easy-to-use templates.",
    icon: Briefcase,
    color: "bg-indigo-100 text-indigo-600 dark:bg-indigo-900/30 dark:text-indigo-400",
    category: "Utility",
  },
  {
    id: "qr-generator",
    slug: "qr-generator",
    title: "QR Generator",
    description: "Create custom QR codes for URLs, text, Wi-Fi, and more instantly.",
    icon: QrCode,
    color: "bg-emerald-100 text-emerald-600 dark:bg-emerald-900/30 dark:text-emerald-400",
    category: "Utility",
  },
  {
    id: "document-editor",
    slug: "document-editor",
    title: "Document Editor",
    description: "A rich-text DOCX editor with formatting, autosave, and exports.",
    icon: FileText,
    color: "bg-blue-100 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400",
    category: "Utility",
  },
  {
    id: "zip-extractor",
    slug: "zip-extractor",
    title: "ZIP Extractor",
    description: "Extract ZIP files or compress multiple files into a single archive.",
    icon: FileArchive,
    color: "bg-cyan-100 text-cyan-600 dark:bg-cyan-900/30 dark:text-cyan-400",
    category: "Utility",
  },
  {
    id: "bg-remover",
    slug: "background-remover",
    title: "Background Remover",
    description: "Automatically remove image backgrounds with high precision AI.",
    icon: Eraser,
    color: "bg-pink-100 text-pink-600 dark:bg-pink-900/30 dark:text-pink-400",
    category: "Image",
  },
  {
    id: "ai-pdf-summary",
    slug: "ai-pdf-summary",
    title: "AI PDF Summary",
    description: "Instantly summarize long PDF documents into key points using AI.",
    icon: Sparkles,
    color: "bg-blue-100 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400",
    category: "AI",
    isAi: true,
  },
  {
    id: "ai-resume-builder",
    slug: "ai-resume-builder",
    title: "AI Resume Builder",
    description: "Generate professional resumes automatically based on your LinkedIn or brief description.",
    icon: FileSignature,
    color: "bg-indigo-100 text-indigo-600 dark:bg-indigo-900/30 dark:text-indigo-400",
    category: "AI",
    isAi: true,
  },
  {
    id: "ai-notes-generator",
    slug: "ai-notes-generator",
    title: "AI Notes Generator",
    description: "Turn audio, messy text, or images into perfectly structured study notes.",
    icon: BrainCircuit,
    color: "bg-violet-100 text-violet-600 dark:bg-violet-900/30 dark:text-violet-400",
    category: "AI",
    isAi: true,
  },
  {
    id: "ai-ocr-enhancement",
    slug: "ai-ocr-enhancement",
    title: "AI OCR Enhancement",
    description: "Not just text extraction! Our AI corrects typos and formats the extracted text perfectly.",
    icon: ScanText,
    color: "bg-orange-100 text-orange-600 dark:bg-orange-900/30 dark:text-orange-400",
    category: "AI",
    isAi: true,
  },
  {
    id: "ai-bg-removal",
    slug: "ai-bg-removal",
    title: "AI Background Removal",
    description: "Flawlessly remove image backgrounds with neural networks. Hair and fur supported.",
    icon: Eraser,
    color: "bg-pink-100 text-pink-600 dark:bg-pink-900/30 dark:text-pink-400",
    category: "AI",
    isAi: true,
  },
];

export function getToolBySlug(slug: string) {
  return toolsConfig.find((tool) => tool.slug === slug);
}
